### ISSUE TITLE
Images only rendering at admin size, not original

### ISSUE THREAD

**Issue by hblackett** [withassociates/slices#129]
In an attachments Slice, images only appear if I call for the :admin size. Using the following will only render the caption, and no image.

```
  <ul class="images">
    <%- slice.images.each do |image| -%>
      <li>
        <%= image_if_present image.asset, :original %>
        <div class="caption"><%= markdown image.caption %></div>
      </li>
    <%- end -%>
  </ul>
```

I've checked the direct paths for admin and original size images, and they both exist (**system/files/.../.../original/file.jpg** and **system/files/.../.../admin/file.jpg**).

**Comment by erino** [comment]
Have you defined any assets with `Slices::Config.add_asset_styles`?

There should be a commented out example in `config/initializers/slices.rb` if you've run the `rails g slices:install` generator

**Comment by hblackett** [comment]
Thanks
