### ISSUE TITLE
[RFC] Replace wiki with in-repo guides

### ISSUE THREAD

**Issue by jgwhite** [withassociates/slices#141]
## Summary

Move the documentation from the wiki to a new directory in the project called `doc` or `guides`. Do some spring cleaning in the process.

## Motivation

Documentation generated from inline comments is great but there is still value in a set of “guides” organised in a cookbook style. This is the purpose the wiki currently serves. Unfortunately, the wiki has gone untended and has fallen out of sync. In part, this is because the wiki is independent of the codebase and easily ignored. Moving the documentation from the wiki into the repo will help us version the two in lockstep.

## Detailed Design

We create a new directory in the project called `doc` or `guides` and add in all guides from the wiki that are still relevant/accurate.

With this in place, any PRs that introduce significant new APIs should include relevant patches to the guides.

## Drawbacks

This does not change the fact that the guides need attention and maintenance. It does not magically fix the problem of keeping the two in sync, but it will allow people to view the guides as they stood at a particular tag or version.

## Alternatives

Leave the wiki in place but pay it more attention.

## Unresolved questions

None at this time.

**Comment by bensymonds** [comment]
:+1: I agree it's hard to keep things in sync, but this will make it easier. And being able to do it (or comment on lack of it :trollface:) as part of PR really helps.

**Comment by calumgunn** [comment]
:+1: Well up for this. Been meaning to "do" the wiki for a while, but it's such a huge task...

**Comment by calumgunn** [comment]
What format would we be into? Markdown?

**Comment by jgwhite** [comment]
@calumgunn yeah, straight up Markdown in a totally flat structure. Working on a PR now.
