### ISSUE TITLE
Defaults handlebars helper

### ISSUE THREAD

**Issue by thomasmarshall** [withassociates/slices#69]
I'm proposing a `defaults` handlebars helper. This could be used in slice templates, page main/meta templates and inside composers etc. Perhaps not a perfect solution – defaults should be defined in the model? – but this works at least. Would be especially useful for `select` fields which might *look* selected by default, but aren't.

```hbs
{{defaults title="Hello world" text="Lorem ipsum dolor sit amet"}}

<input type="text" id="slices-{{id}}-title" placeholder="Title…" value="{{title}}">
<textarea id="slices-{{id}}-text" placeholder="Text…">{{text}}</textarea>
```

```js
Handlebars.registerHelper('defaults', function(options) {
  _.defaults(this, options.hash);
});
```

**Comment by jgwhite** [comment]
Interesting proposal. We are definitely missing a way to configure slice data when they’re first added to the page.

I’d be inclined to make it more specific that this helper mutates the context. Maybe call it `{{apply-defaults}}` ?

**Comment by thomasmarshall** [comment]
I agree, `{{apply-defaults}}` is definitely clearer.

**Comment by jgwhite** [comment]
Yeah, probably is. Though I think kebab-case is more readable in general. Maybe alias them?
